alter table public.menu_items
  add column if not exists vip_price numeric(12, 2);

alter table public.menu_items
  add column if not exists pricing_mode text not null default 'unit' check (pricing_mode in ('unit', 'kg')),
  add column if not exists default_qty numeric(12, 3) not null default 1,
  add column if not exists qty_step numeric(12, 3) not null default 1,
  add column if not exists stock_sku text not null default '';

alter table public.menu_items
  alter column vip_price drop not null,
  alter column vip_price drop default;

-- Stations referenced by this seed (001 may not include VIP Bar yet).
insert into public.production_stations (name, position)
values
  ('Bar', 1),
  ('Kitchen', 2),
  ('Butcher House', 3),
  ('VIP Bar', 4),
  ('Coffee House', 5)
on conflict (name) do update set
  position = excluded.position,
  active = true,
  updated_at = now();

insert into public.menu_categories (name, position)
values
  ('Meat', 5),
  ('Beer', 6),
  ('Soft Drinks', 7),
  ('Water', 8),
  ('Other Drinks', 9),
  ('Spirits', 10)
on conflict (name) do update set
  position = excluded.position,
  active = true,
  updated_at = now();

insert into public.menu_items (
  id,
  name_en,
  name_am,
  category,
  price,
  vip_price,
  cost,
  station,
  emoji,
  pricing_mode,
  default_qty,
  qty_step,
  stock_sku,
  active
)
values
  ('tri-sga', 'Tri Sga', '', 'Meat', 4000, 5000, 0, 'Butcher House', 'TS', 'unit', 1, 1, 'tri-sga', true),
  ('dulet', 'Dulet', '', 'Meat', 700, 1000, 0, 'Butcher House', 'D', 'unit', 1, 1, 'dulet', true),
  ('gaz-layt', 'Gaz Layt', '', 'Meat', 4000, 5000, 0, 'Butcher House', 'GL', 'unit', 1, 1, 'gaz-layt', true),
  ('godn', 'Godn', '', 'Meat', 4000, 5000, 0, 'Butcher House', 'G', 'unit', 1, 1, 'godn', true),
  ('grill-tibs', 'Grill Tibs', '', 'Meat', 4000, 5000, 0, 'Butcher House', 'GT', 'unit', 1, 1, 'grill-tibs', true),
  ('katelo', 'Katelo', '', 'Meat', 4000, 5000, 0, 'Butcher House', 'K', 'unit', 1, 1, 'katelo', true),
  ('shekla', 'Shekla', '', 'Meat', 4000, 5000, 0, 'Butcher House', 'S', 'unit', 1, 1, 'shekla', true),
  ('tebit', 'Tebit', '', 'Meat', 0, null, 0, 'Butcher House', 'T', 'unit', 1, 1, 'tebit', true),
  ('wolando', 'Wolando', '', 'Meat', 4000, 5000, 0, 'Butcher House', 'W', 'unit', 1, 1, 'wolando', true),
  ('zlzl', 'Zlzl', '', 'Meat', 4000, 5000, 0, 'Butcher House', 'Z', 'unit', 1, 1, 'zlzl', true),
  ('gubet', 'Gubet', '', 'Meat', 1200, null, 0, 'Butcher House', 'G', 'unit', 1, 1, 'gubet', true),
  ('mlas-sember', 'Mlas Sember', '', 'Meat', 2000, null, 0, 'Butcher House', 'MS', 'unit', 1, 1, 'mlas-sember', true),
  ('ye-fyel-dulet', 'Ye Fyel Dulet', '', 'Meat', 1000, 1250, 0, 'Butcher House', 'YFD', 'unit', 1, 1, 'ye-fyel-dulet', true),
  ('collection-yefyel', 'Collection Yefyel', '', 'Meat', 4000, 5000, 0, 'Butcher House', 'CY', 'unit', 1, 1, 'collection-yefyel', true),
  ('yefyel', 'Yefyel', '', 'Meat', 4000, 5000, 0, 'Butcher House', 'Y', 'unit', 1, 1, 'yefyel', true),
  ('yeberi-dulet', 'Yeberi Dulet', '', 'Meat', 1500, 2000, 0, 'Butcher House', 'YD', 'unit', 1, 1, 'yeberi-dulet', true),
  ('draft-beer', 'Draft Beer', '', 'Beer', 1500, 2000, 0, 'Bar', 'DB', 'unit', 1, 1, 'draft-beer', true),
  ('bedeli', 'Bedelle', '', 'Beer', 140, 300, 0, 'Bar', 'B', 'unit', 1, 1, 'bedeli', true),
  ('arada', 'Arada', '', 'Beer', 140, 300, 0, 'Bar', 'A', 'unit', 1, 1, 'arada', true),
  ('heineken', 'Heineken', '', 'Beer', 140, 300, 0, 'Bar', 'H', 'unit', 1, 1, 'heineken', true),
  ('bottled-beer', 'Bottled Beer', '', 'Beer', 0, null, 0, 'Bar', 'BB', 'unit', 1, 1, 'bottled-beer', true),
  ('dashen', 'Dashen', '', 'Beer', 140, 300, 0, 'Bar', 'D', 'unit', 1, 1, 'dashen', true),
  ('st-george', 'St. George', '', 'Beer', 120, 300, 0, 'Bar', 'SG', 'unit', 1, 1, 'st-george', true),
  ('castel-beer', 'Castel', '', 'Beer', 120, 300, 0, 'Bar', 'CB', 'unit', 1, 1, 'castel-beer', true),
  ('habesha', 'Habesha', '', 'Beer', 120, 300, 0, 'Bar', 'H', 'unit', 1, 1, 'habesha', true),
  ('ngus', 'Ngus', '', 'Beer', 120, 300, 0, 'Bar', 'N', 'unit', 1, 1, 'ngus', true),
  ('harar', 'Harar', '', 'Beer', 120, 300, 0, 'Bar', 'H', 'unit', 1, 1, 'harar', true),
  ('sprite', 'Sprite', '', 'Soft Drinks', 120, 300, 0, 'Bar', 'S', 'unit', 1, 1, 'sprite', true),
  ('coca-cola', 'Coca-Cola', '', 'Soft Drinks', 120, 300, 0, 'Bar', 'CC', 'unit', 1, 1, 'coca-cola', true),
  ('fanta', 'Fanta', '', 'Soft Drinks', 120, 300, 0, 'Bar', 'F', 'unit', 1, 1, 'fanta', true),
  ('mirinda', 'Mirinda', '', 'Soft Drinks', 120, 300, 0, 'Bar', 'M', 'unit', 1, 1, 'mirinda', true),
  ('7-up', '7UP', '', 'Soft Drinks', 120, 300, 0, 'Bar', '7U', 'unit', 1, 1, '7-up', true),
  ('half-liter-water', '0.5 Liter Water', '', 'Water', 60, 100, 0, 'Bar', 'H', 'unit', 1, 1, 'half-liter-water', true),
  ('one-liter-water', '1 Liter Water', '', 'Water', 80, 100, 0, 'Bar', 'O', 'unit', 1, 1, 'one-liter-water', true),
  ('ambuha', 'Ambuha', '', 'Water', 80, 200, 0, 'Bar', 'A', 'unit', 1, 1, 'ambuha', true),
  ('awash', 'Awash Wayne', '', 'Water', 80, 200, 0, 'Bar', 'A', 'unit', 1, 1, 'awash', true),
  ('acacia', 'Acacia Wayne', '', 'Water', 80, 200, 0, 'Bar', 'A', 'unit', 1, 1, 'acacia', true),
  ('axumit', 'Axumit Wayne', '', 'Water', 80, 200, 0, 'Bar', 'A', 'unit', 1, 1, 'axumit', true),
  ('gebeta-water', 'Gebeta Wayne', '', 'Water', 1200, 2000, 0, 'Bar', 'GW', 'unit', 1, 1, 'gebeta-water', true),
  ('kemila', 'Kemila Wayne', '', 'Water', 2000, 3000, 0, 'Bar', 'K', 'unit', 1, 1, 'kemila', true),
  ('guder', 'Guder Wayne', '', 'Water', 1500, 2000, 0, 'Bar', 'G', 'unit', 1, 1, 'guder', true),
  ('refi-valley', 'Refi Valley Wayne', '', 'Water', 1500, 2000, 0, 'Bar', 'RV', 'unit', 1, 1, 'refi-valley', true),
  ('draft-beer-other', 'Draft Beer', '', 'Other Drinks', 1500, 2000, 0, 'Bar', 'DBO', 'unit', 1, 1, 'draft-beer-other', true),
  ('areki', 'Areki', '', 'Other Drinks', 0, null, 0, 'Bar', 'A', 'unit', 1, 1, 'areki', true),
  ('absolute-elyx', 'Absolute Elyx', '', 'Spirits', 16000, null, 0, 'Bar', 'AE', 'unit', 1, 1, 'absolute-elyx', true),
  ('amarula', 'Amarula', '', 'Spirits', 20000, 600, 0, 'Bar', 'A', 'unit', 1, 1, 'amarula', true),
  ('bacardi-075l', 'Bacardi 0.75L', '', 'Spirits', 12000, null, 0, 'Bar', 'B', 'unit', 1, 1, 'bacardi-075l', true),
  ('bacardi-1l', 'Bacardi 1L', '', 'Spirits', 16000, null, 0, 'Bar', 'B', 'unit', 1, 1, 'bacardi-1l', true),
  ('ballantines', 'Ballantine''s', '', 'Spirits', 20000, null, 0, 'Bar', 'B', 'unit', 1, 1, 'ballantines', true),
  ('beehive-vsop', 'Beehive VSOP', '', 'Spirits', 25000, null, 0, 'Bar', 'BV', 'unit', 1, 1, 'beehive-vsop', true),
  ('black-label', 'Black Label', '', 'Spirits', 16000, 700, 0, 'VIP Bar', 'BL', 'unit', 1, 1, 'black-label', true),
  ('black-label-2l', 'Black Label 2L', '', 'Spirits', 35000, null, 0, 'VIP Bar', 'BL', 'unit', 1, 1, 'black-label-2l', true),
  ('black-ruby', 'Black Ruby', '', 'Spirits', 20000, null, 0, 'Bar', 'BR', 'unit', 1, 1, 'black-ruby', true),
  ('blue-label', 'Blue Label', '', 'Spirits', 80000, null, 0, 'Bar', 'BL', 'unit', 1, 1, 'blue-label', true),
  ('chianti', 'Chianti', '', 'Spirits', 18000, null, 0, 'Bar', 'C', 'unit', 1, 1, 'chianti', true),
  ('ciroc', 'Ciroc', '', 'Spirits', 9500, null, 0, 'Bar', 'C', 'unit', 1, 1, 'ciroc', true),
  ('camus-vsop', 'Camus VSOP', '', 'Spirits', 30000, null, 0, 'Bar', 'CV', 'unit', 1, 1, 'camus-vsop', true),
  ('camino-tequila', 'Camino Tequila', '', 'Spirits', 15000, 500, 0, 'Bar', 'CT', 'unit', 1, 1, 'camino-tequila', true),
  ('captain-morgan', 'Captain Morgan', '', 'Spirits', 16000, null, 0, 'Bar', 'CM', 'unit', 1, 1, 'captain-morgan', true),
  ('casamigos', 'Casamigos', '', 'Spirits', 45000, 1200, 0, 'Bar', 'C', 'unit', 1, 1, 'casamigos', true),
  ('tequila', 'Tequila', '', 'Spirits', 0, null, 0, 'Bar', 'T', 'unit', 1, 1, 'tequila', true),
  ('castel-champagne', 'Castel Champagne', '', 'Spirits', 6000, null, 0, 'Bar', 'CC', 'unit', 1, 1, 'castel-champagne', true),
  ('castel-wine', 'Castel Wine', '', 'Spirits', 6000, null, 0, 'Bar', 'CW', 'unit', 1, 1, 'castel-wine', true),
  ('chivas-12', 'Chivas 12', '', 'Spirits', 17000, null, 0, 'Bar', 'C', 'unit', 1, 1, 'chivas-12', true),
  ('chivas-18', 'Chivas 18', '', 'Spirits', 33000, null, 0, 'Bar', 'C', 'unit', 1, 1, 'chivas-18', true),
  ('courvoisier-vs', 'Courvoisier VS', '', 'Spirits', 22000, null, 0, 'Bar', 'CV', 'unit', 1, 1, 'courvoisier-vs', true),
  ('dech-vodka', 'Dech Vodka', '', 'Spirits', 11000, null, 0, 'Bar', 'DV', 'unit', 1, 1, 'dech-vodka', true),
  ('delamain-cognac', 'Delamain Cognac', '', 'Spirits', 45000, null, 0, 'Bar', 'DC', 'unit', 1, 1, 'delamain-cognac', true),
  ('dimple', 'Dimple', '', 'Spirits', 30000, null, 0, 'Bar', 'D', 'unit', 1, 1, 'dimple', true),
  ('disaronno', 'Disaronno', '', 'Spirits', 25000, null, 0, 'Bar', 'D', 'unit', 1, 1, 'disaronno', true),
  ('don-julio', 'Don Julio', '', 'Spirits', 80000, null, 0, 'Bar', 'DJ', 'unit', 1, 1, 'don-julio', true),
  ('premium', 'Premium', '', 'Spirits', 35000, 1100, 0, 'Bar', 'P', 'unit', 1, 1, 'premium', true),
  ('don-julio-small', 'Don Julio Small', '', 'Spirits', 18000, null, 0, 'Bar', 'DJS', 'unit', 1, 1, 'don-julio-small', true),
  ('double-black', 'Double Black', '', 'Spirits', 16000, 600, 0, 'Bar', 'DB', 'unit', 1, 1, 'double-black', true),
  ('fernet-branca', 'Fernet Branca', '', 'Spirits', 6000, null, 0, 'Bar', 'FB', 'unit', 1, 1, 'fernet-branca', true),
  ('gebeta-2l', 'Gebeta 2L', '', 'Spirits', 12000, 700, 0, 'Bar', 'G2', 'unit', 1, 1, 'gebeta-2l', true),
  ('glass-wine', 'Glass Wine', '', 'Spirits', 0, null, 0, 'Bar', 'GW', 'unit', 1, 1, 'glass-wine', true),
  ('glenfiddich-12', 'Glenfiddich 12', '', 'Spirits', 18000, null, 0, 'Bar', 'G', 'unit', 1, 1, 'glenfiddich-12', true),
  ('glenfiddich-15', 'Glenfiddich 15', '', 'Spirits', 25000, null, 0, 'Bar', 'G', 'unit', 1, 1, 'glenfiddich-15', true),
  ('glenfiddich-18', 'Glenfiddich 18', '', 'Spirits', 33000, null, 0, 'Bar', 'G', 'unit', 1, 1, 'glenfiddich-18', true),
  ('godfather', 'Godfather', '', 'Spirits', 25000, null, 0, 'Bar', 'G', 'unit', 1, 1, 'godfather', true),
  ('gold', 'Gold', '', 'Spirits', 23000, null, 0, 'Bar', 'G', 'unit', 1, 1, 'gold', true),
  ('gordons', 'Gordon''s', '', 'Spirits', 10000, 600, 0, 'Bar', 'G', 'unit', 1, 1, 'gordons', true),
  ('grey-goose', 'Grey Goose', '', 'Spirits', 17000, null, 0, 'Bar', 'GG', 'unit', 1, 1, 'grey-goose', true),
  ('hendricks', 'Hendrick''s', '', 'Spirits', 18000, null, 0, 'Bar', 'H', 'unit', 1, 1, 'hendricks', true),
  ('hennessy-vs', 'Hennessy VS', '', 'Spirits', 26000, null, 0, 'Bar', 'HV', 'unit', 1, 1, 'hennessy-vs', true),
  ('hennessy-vsop', 'Hennessy VSOP', '', 'Spirits', 35000, null, 0, 'Bar', 'HV', 'unit', 1, 1, 'hennessy-vsop', true),
  ('jc-palace', 'J.C. Palace', '', 'Spirits', 14000, null, 0, 'Bar', 'JCP', 'unit', 1, 1, 'jc-palace', true),
  ('jb', 'J&B', '', 'Spirits', 15000, null, 0, 'Bar', 'JB', 'unit', 1, 1, 'jb', true),
  ('jack-daniels', 'Jack Daniel''s', '', 'Spirits', 18000, null, 0, 'Bar', 'JD', 'unit', 1, 1, 'jack-daniels', true),
  ('jagermeister', 'J??germeister', '', 'Spirits', 16000, 500, 0, 'Bar', 'J', 'unit', 1, 1, 'jagermeister', true),
  ('jim-beam', 'Jim Beam', '', 'Spirits', 14000, null, 0, 'Bar', 'JB', 'unit', 1, 1, 'jim-beam', true),
  ('mango-juice', 'Mango Juice', '', 'Spirits', 1000, null, 0, 'Bar', 'MJ', 'unit', 1, 1, 'mango-juice', true),
  ('martini', 'Martini', '', 'Spirits', 15000, null, 0, 'Bar', 'M', 'unit', 1, 1, 'martini', true),
  ('monkey-shoulder', 'Monkey Shoulder', '', 'Spirits', 18000, null, 0, 'Bar', 'MS', 'unit', 1, 1, 'monkey-shoulder', true),
  ('platinum', 'Platinum', '', 'Spirits', 35000, null, 0, 'Bar', 'P', 'unit', 1, 1, 'platinum', true),
  ('red-bull', 'Red Bull', '', 'Spirits', 1000, null, 0, 'Bar', 'RB', 'unit', 1, 1, 'red-bull', true),
  ('roberto-cavalli-vodka', 'Roberto Cavalli Vodka', '', 'Spirits', 20000, null, 0, 'Bar', 'RCV', 'unit', 1, 1, 'roberto-cavalli-vodka', true),
  ('red-label', 'Red Label', '', 'Spirits', 12000, null, 0, 'Bar', 'RL', 'unit', 1, 1, 'red-label', true),
  ('sambuca', 'Sambuca', '', 'Spirits', 15000, 500, 0, 'Bar', 'S', 'unit', 1, 1, 'sambuca', true),
  ('small-jagermeister', 'Small J??germeister', '', 'Spirits', 2000, null, 0, 'Bar', 'SJ', 'unit', 1, 1, 'small-jagermeister', true),
  ('small-vodka', 'Small Vodka', '', 'Spirits', 1500, null, 0, 'Bar', 'SV', 'unit', 1, 1, 'small-vodka', true),
  ('singleton', 'Singleton', '', 'Spirits', 20000, null, 0, 'Bar', 'S', 'unit', 1, 1, 'singleton', true),
  ('smirnoff', 'Smirnoff', '', 'Spirits', 30000, null, 0, 'Bar', 'S', 'unit', 1, 1, 'smirnoff', true),
  ('st-remi-1l', 'St. Remi 1L', '', 'Spirits', 0, null, 0, 'Bar', 'SR', 'unit', 1, 1, 'st-remi-1l', true),
  ('stockinia-05l', 'Stockinia 0.5L', '', 'Spirits', 4500, null, 0, 'Bar', 'S', 'unit', 1, 1, 'stockinia-05l', true),
  ('stockinia-1l', 'Stockinia 1L', '', 'Spirits', 9000, null, 0, 'Bar', 'S', 'unit', 1, 1, 'stockinia-1l', true),
  ('vecchia-romagna', 'Vecchia Romagna', '', 'Spirits', 20000, null, 0, 'Bar', 'VR', 'unit', 1, 1, 'vecchia-romagna', true),
  ('white-horse', 'White Horse', '', 'Spirits', 14000, null, 0, 'Bar', 'WH', 'unit', 1, 1, 'white-horse', true),
  ('winter-05l', 'Winter 0.5L', '', 'Spirits', 5000, null, 0, 'Bar', 'W', 'unit', 1, 1, 'winter-05l', true),
  ('xo-hennessy', 'XO Hennessy', '', 'Spirits', 100000, null, 0, 'Bar', 'XH', 'unit', 1, 1, 'xo-hennessy', true),
  ('zonin-wine', 'Zonin Wine', '', 'Spirits', 2000, null, 0, 'Bar', 'ZW', 'unit', 1, 1, 'zonin-wine', true),
  ('5-label', '5 Label', '', 'Spirits', 18000, null, 0, 'Bar', '5L', 'unit', 1, 1, '5-label', true)
on conflict (id) do update set
  name_en = excluded.name_en,
  name_am = excluded.name_am,
  category = excluded.category,
  price = excluded.price,
  vip_price = excluded.vip_price,
  cost = excluded.cost,
  station = excluded.station,
  emoji = excluded.emoji,
  pricing_mode = excluded.pricing_mode,
  default_qty = excluded.default_qty,
  qty_step = excluded.qty_step,
  stock_sku = excluded.stock_sku,
  active = true,
  updated_at = now();


